server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # 配置Redis IP地址
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka