server:
  port: 2000
spring:
  application:
    name: atguigu-crowd-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/project_crowd?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#eureka 路径
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
# mapper 扫描路径
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
#log 配置
logging:
  level:
    level:
      com.atguigu.crowd.mapper: debug
      com.atguigu.crowd.test: debug
